services:
  db:
    image: postgres:16-alpine
    container_name: ta_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: ta_backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      SEED: ${SEED:-1}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173}
      SEED_USERS_FILE: /app/seed_users.json
    volumes:
      - ${SEED_USERS_FILE:-./backend/seed_users.json}:/app/seed_users.json:ro
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    container_name: ta_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"


volumes:
  db_data:
